-- init.sql

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    week_days VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Garantir que as colunas city e week_days existam
ALTER TABLE IF EXISTS users
ADD COLUMN IF NOT EXISTS city VARCHAR(255) NOT NULL,
ADD COLUMN IF NOT EXISTS week_days VARCHAR(255) NOT NULL;
