services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres12
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - sensedia_challenge_api_data:/var/lib/postgresql/data

volumes:
  sensedia_challenge_api_data:
